import { type } from "arktype";

export const beInCryptoSchema = type({
  id: "number",
  title: "string.lower |> string.trim",
  slug: "string",
  type: "string",
  salaryStart: "number | null",
  salaryEnd: "number | null",
  applyLink: "string",
  applyEmail: "string | null",
  shortDescription: "string | null",
  description: "string",
  applicants: "number",
  createdAt: "string",
  updatedAt: "string",
  paidInCrypto: "boolean",
  publishedDate: "string.date.iso.parse",
  unpublishedDate: "string | null",
  locale: "string",
  closed: "boolean",
  featFromDate: "string | null",
  featToDate: "string | null",
  numberOfViews: "number",
  isStartUp: "boolean",
  company: {
    id: "number",
    name: "string >= 2 |> string.lower |> string.trim",
    website: "string",
    email: "string | null",
    logoURL: "string | null",
    description: "string",
    createdAt: "string",
    updatedAt: "string",
    slug: "string",
    locale: "string",
  },
  jobTags: type({
    id: "number",
    slug: type("string.lower |> string.trim"),
    label: "string.lower |> string.trim",
    createdAt: "string",
    updatedAt: "string",
    locale: "string",
    isNonTech: "boolean | null",
  }).array(),
  locationTags: type({
    id: "number",
    label: "string",
    slug: "string",
    assignable: "boolean",
    createdAt: "string",
    updatedAt: "string",
    locale: "string",
    country: "boolean",
  }).array(),
});
