[project]
name = "my-crawler"
version = "0.0.1"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.9,<4.0"
dependencies = [
    "crawl4ai>=0.5.0.post8",
    "crawlee[playwright]",
]

